### ISSUE TITLE
requests over closed connections should be retried

### ISSUE THREAD

**Issue by blampe** [uber/tchannel-python#289]
```
def send_request(self, request):
    assert not self.closed
```

If the connection is closed the request should be re-tried on another peer.

**Comment by blampe** [comment]
cc @junchaowu @breerly @abhinav @dnathe4th @alexdiao

**Comment by junchaowu** [comment]
the close could happen at any stage. So maybe just remove the assert and capture the network error to do retry.

**Comment by alexdiao** [comment]
Looks like it's fiexed in 0.19.0?

**Comment by abhinav** [comment]
@alexdiao The 0.19 branch was renamed to 0.21 because we had to make two unplanned minor releases. This change was ported back to 0.20.  It's present in [0.20.1](https://github.com/uber/tchannel-python/blob/master/CHANGES.rst#0201-2015-11-12).

But yeah, we can probably close this issue now. Thanks.

**Comment by alexdiao** [comment]
cool let me see if it works.
