### ISSUE TITLE
Should tracing be ON by default?

### ISSUE THREAD

**Issue by yurishkuro** [uber/tchannel-python#440]
Currently in the constructor the default is `trace=None` which ends up turning off the sampling of the spans to 0. 

Should this perhaps be `trace=True` by default?  If the `opentracing.tracer` is not initialized, then `trace=True` still results in no tracing, so it feels like an unnecessary switch, only for very special cases like Hyperbahn requests.

@abhinav @blampe @thepaulm

**Comment by blampe** [comment]
This was intentional because previously `trace=True` would result in failures with an uninitialized tracer. If `trace=True` is a no-op without a concrete tracer then this is fine. We just don't want tests submitting traces by default or people getting connection errors locally due to missing dependencies.

**Comment by yurishkuro** [comment]
The tchannel instances default to `opentracing.tracer` if not given an explicit instance of the tracer, and `opentracing.tracer` by default is a Noop tracer. So the application needs to proactively instantiate a concrete tracer (including in tests) in order to submit any spans.
